sudo: required
language: go
go:
- 1.8
services:
- docker
after_success:
- source ./build/travis-utils.sh
- if is_travis_push_env; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
- if is_travis_push_env; then make push; fi
- if is_travis_release_env; then make push-latest; fi
env:
  global:
  - secure: d+SsriniNhjNHyTDqFYWYKbDl3nW46x1X3N/Tp6uxcegP/OPqJqzaBHVj3+BzO88oSQ95wBJ5wArsB2ysX8Ap08ylDJwzOLg2tl9XaTa7Ie0M30trj+t5uRx/wltcw0U47eW1mzWSdf++dirVoSwVvX3pRPxvNa0WjwAUyMtYuZDUwy8kJp6OVpKquDc3MWZvLtpMfZG8egGWqUKE2vuBHTnY0r+EQcPFVJIefmEeF08COKjrGOYYAT0Hbl81tPoST2pxIR7INDmqbgOQ/aL/Uf9KRyZqkxPUV5NXy9kcnZE36gWclW1r75zSbX2mMbIXa0YHzCcljCsmNeMC0c1mIjontWjHYKf7dLeJkk8heEiSJF2FvsA7iez3lwDcd65ZJV2e/LXjJ4BXdQGEkCX9qhNavXqoNQyzP1jm/SuV4YdXfk7Eq8IFFT3SOai/jqP0uoFqiLuLhPW/wbeK03wEI+rOigvfuYQ1qCSlMs+yebHczD78syBxiTnx0Ns2exq+TGORBSazXxqyAZXNskYM8YdPqpQW4GJ+0vytL3dpKf4lraF2duZxXpZSlVpZMMrKpd3YbkvHm8lEwWJfLvIoZumw96hTVAoKUSTzK9h+gI0v64vP9fjKKEFjYxR5v7TNZtTNSP4VXUIHUNUa+2Yn5u1XdEHgLl9UKptBOs8/XM=
  - secure: DCkJCDUsvyLZIWhKwCFUm8p6EiWugevdG1n9QM7eTFrzLCB6ZCf+zMPXzptWzAEhCSIPb/M5LJrDnUXQ9Whw9Y0uw3fI8wJfCGmlK1982ouEzRqg+G1Oaj+ULBsP1tBBhyv1lqHOYRuyRYtoZmNsFB+q5VKeUvMPAhUlaqpVDTZI0mWTxTLRo1fMF3FAsdWshGjMDz+9BLJ8YfVXjpOHuppls6LYfJI10Nfdc678oRRcmeh1JrapeUetmotLJuDUtM14Kgfl3URUEWTVQO2ALsr6JuRVWoGoYpNkLHsn1fCEL8XCNTA5UVcfGEIOmNA/v34M3DDtANOQk+ka6uatboux3KH7NgL1AGX6GfJOjXZ8QpsKYto7Fmxzj4pxsFSbN1TRh+2+Uy1c9uh6oMCsP3OTw3I6yxIAWPEu2MfZT4ANddspUn7FdoJgbSTSuuyv5uWTIWwUh1waxOBZZjfUoV1l0w8ZMmykNAretj1fMT73ten+xOr2hKojyfp55zQ3r7ESIOBA1TnUUF2B9T0Cba6Dn2mklOepwhCZA4QjNLt6bud721CaMxJ7mh8BYj0NZYBKpFTVT47BEWP9CRMXveeGAhzTiBLScfzdEHTeyA9mlbUeTTFfZ3qFGdZQ74A1hRbuH+taOWP9cdjc5qEGcEguXEKyMpT+05lYTcM+jyQ=
