apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: opa-kube-mgmt
build:
  artifacts:
    - image: openpolicyagent/kube-mgmt
      ko:
        fromImage: alpine:3.16.7
        main: ./cmd/kube-mgmt/.../
        ldflags:
          - "-X github.com/open-policy-agent/kube-mgmt/pkg/version.Version={{.VERSION}}"
          - "-X github.com/open-policy-agent/kube-mgmt/pkg/version.Git={{.COMMIT}}"
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      context: .
      hooks:
        after:
          - command: ["sh", "-c", "just _latest"]
  local:
    push: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: kube-mgmt
        chartPath: charts/opa-kube-mgmt
        wait: true
        setValues:
          e2e: true
        valuesFiles:
          - "test/e2e/{{.E2E_TEST}}/values.yaml"
        upgradeOnChange: false
        skipBuildDependencies: true
        artifactOverrides:
          mgmt.image: openpolicyagent/kube-mgmt
        imageStrategy:
          helm: {}
