apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: opa
build:
  artifacts:
    - image: openpolicyagent/kube-mgmt
      context: .
      docker:
        buildArgs:
          VERSION: "{{.VERSION}}"
          COMMIT: "{{.COMMIT}}"
  local:
    push: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: kube-mgmt
        chartPath: charts/opa
        wait: true
        setValues:
          e2e: true
        valuesFiles:
          - "test/e2e/{{.E2E_TEST}}/values.yaml"
        upgradeOnChange: false
        skipBuildDependencies: true
        artifactOverrides:
          mgmt.image: openpolicyagent/kube-mgmt
        imageStrategy:
          helm: {}
