name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - "logo/**"
      - "examples/**"
      - "README.md"
      - "charts/opa-kube-mgmt/README.md"
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      - "feat/*"
      - "fix/*"
jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.local/share/helm/plugins
          key: go-tools-${{ hashFiles('devbox.json', 'go.mod', 'go.sum') }}
          restore-keys: |
            go-tools-
      - uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true
      - run: devbox run -- just test
      - name: publish helm lint report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: "build/test-results/helm-unittest/lint.xml"
          check_name: "Helm Lint Tests"
          fail_on_failure: true
          detailed_summary: true
          include_passed: true
      - name: publish helm unit test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: "build/test-results/helm-unittest/unit.xml"
          check_name: "Helm Unit Tests"
          fail_on_failure: true
          detailed_summary: true
          include_passed: true
      - run: devbox run -- just all && devbox run -- just test-e2e-all
      - name: publish e2e test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: "build/test-results/chainsaw/*.xml"
          check_name: "E2E Tests"
          fail_on_failure: true
          detailed_summary: true
          include_passed: true
      - name: failure logs
        if: ${{ failure() }}
        run: |
          echo "---------------------------------------"
          kubectl get all
          echo "---------------------------------------"
          kubectl describe po kube-mgmt-opa-kube-mgmt || true
          echo "---------------------------------------"
          kubectl logs -l app=kube-mgmt-opa-kube-mgmt -c opa --tail=-1
          echo "---------------------------------------"
          kubectl logs -l app=kube-mgmt-opa-kube-mgmt -c mgmt --tail=-1
          echo "---------------------------------------"
